<?xml version="1.0"?>
<package format="3">
  <name>so101_bridge</name>
  <version>0.0.1</version>
  <description>MuJoCo-ROS2 bridge for the SO-101 arm (Imitation Machines technical exercise)</description>
  <maintainer email="you@example.com">bennytay</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
